### ISSUE TITLE
add option 5) Ver inventario in main menu

### ISSUE THREAD

**Issue by Japoivvb** [albertsalom/SHOP_DAM#1]
1. add new option in main menu, click on it or typing 5 a new window must appear with data loaded in inventory as show in below picture

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb + details

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

![image](https://github.com/albertsalom/SHOP_DAM/assets/36648472/71ae54dd-2ff0-4fba-939d-500b4b74265f)

**Comment by albertsalom** [comment]
Add new option in main menu
![Captura de pantalla 2024-06-03 194600](https://github.com/albertsalom/SHOP_DAM/assets/159912492/7eb0f621-89b2-4931-bd02-b21221223008)

Click on it or typing 5 a new window must appear with data loaded in inventory
![Captura de pantalla 2024-06-03 194846](https://github.com/albertsalom/SHOP_DAM/assets/159912492/83047084-ca6c-4cd6-a867-2853bb47e83e)

**Comment by Japoivvb** [comment]
1. ok, but stock and disponible cols are mixing values
2. ok
3. ko, you use 2 instead 1 issue enumeration
4. ok
5. ok
Well done @albertsalom
