### ISSUE TITLE
UF2 Tener productos clasificados como deluxe

### ISSUE THREAD

**Issue by Japoivvb** [albertsalom/SHOP_DAM#2]
añadir atributo deluxe a producto como true para precios publicos de mas de 100€, se ha de mostrar en la opcion 5 de menu

**Comment by albertsalom** [comment]
![image](https://github.com/albertsalom/SHOP_DAM/assets/159912492/03b556d2-0289-45ef-bdfa-e61b2a8f34d9)

**Comment by albertsalom** [comment]
![image](https://github.com/albertsalom/SHOP_DAM/assets/159912492/447daa68-f615-40e6-8101-00f8f66faf35)

**Comment by Japoivvb** [comment]
not in scope
